/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Meshy_AI_Extract_only_the_sky__0616035345_generate_collar_jersey.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/collar_jersey.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_node.geometry} material={nodes.mesh_node.material} />
    </group>
  )
}

useGLTF.preload('/models/collar_jersey.glb')
